from enum import Enum


class MavMessageType(Enum):
    """
    Enum for MAVLink message types.
    """

    UAVIONIX_ADSB_OUT_CFG = 10001
    UAVIONIX_ADSB_OUT_DYNAMIC = 10002
    UAVIONIX_ADSB_TRANSCEIVER_HEALTH_REPORT = 10003
    UAVIONIX_ADSB_OUT_CFG_REGISTRATION = 10004
    UAVIONIX_ADSB_OUT_CFG_FLIGHTID = 10005
    UAVIONIX_ADSB_GET = 10006
    UAVIONIX_ADSB_OUT_CONTROL = 10007
    UAVIONIX_ADSB_OUT_STATUS = 10008
