name: Bump version files on tag push

on:
  push:
    tags:
      - 'v*'

jobs:
  bump-version:
    name: Update version files
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update pyproject.toml and conf.py
        run: |
          VERSION=${{ steps.tag.outputs.VERSION }}
          echo "🔧 Setting version to $VERSION"
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          sed -i "s/^release = \".*\"/release = \"$VERSION\"/" docs/source/conf.py
          sed -i "s/^version = \".*\"/version = \"${VERSION%.*}\"/" docs/source/conf.py

      - name: Commit and push version updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -am "Auto bump version files to ${{ steps.tag.outputs.VERSION }}"
          git push origin HEAD:main
